version: 0.0
os: linux
files:
  - source: /
    destination: /ec2-user/new_app
    overwrite: yes

permissions:
  - object: /ec2-user/new_app
    pattern: '**'
    owner: 'ec2-user'
    group: 'ec2-user'

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 180
      runas: ec2-user