name: release version publish

on: [push]

jobs:
  publish-release:
    name: publish release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install node dependencies
        run: yarn install

      - name: Build node application
        run: yarn build

      - name: ssh test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker exec node-api pm2 list